### ISSUE TITLE
Unable to read TIGER 2.2

### ISSUE THREAD

**Issue by FilippoC** [andreasvc/disco-dop#45] opened 2017-01-09 08:11 UTC
Hello,
I'm trying to transform the Tiger 2.2 corpus in a more usable format :
discodop treetransforms tiger_release_aug07.corrected.16012013.xml test.out --inputfmt=tiger --outputfmt=bracket --ensureroot=ROOT --removeempty
discodop treetransforms tiger.corrected.xml test.out --inputfmt=tiger --outputfmt=bracket --ensureroot=ROOT --removeempty

With the two version I got the same error :
Traceback (most recent call last):
  File "/home/filippo/.local/bin/discodop", line 4, in <module>
    __import__('pkg_resources').run_script('disco-dop==0.5.1', 'discodop')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/EGG-INFO/scripts/discodop", line 33, in <module>
    getattr(__import__('discodop.cli', fromlist=[cmd]), cmd)()
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/cli.py", line 326, in treetransforms
    for key, item in trees:
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/cli.py", line 320, in <genexpr>
    trees = ((key, canonicalize(item.tree) and item)
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/treebank.py", line 132, in itertrees
    yield n, self._parsetree(a)
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/treebank.py", line 176, in _parsetree
    item = self._parse(block)
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/treebank.py", line 381, in _parse
    self.functions, self.morphology, self.lemmas)
  File "/home/filippo/.local/lib/python3.5/site-packages/disco_dop-0.5.1-py3.5-linux-x86_64.egg/discodop/treebank.py", line 472, in exporttree
    children[source[PARENT]].append((n, source))
KeyError: '502'

Is that because of an error in the corpus ?
Thanks

**Comment by andreasvc** [comment] 2017-01-09 12:04
Thanks for the report. I never really understood the point of the TigerXML format, it's quite a direct translation of the Negra export format which is more efficiently readable. I fixed the bug you reported in the latest commit, but it turns out the so-called "corrected" Tiger XML version introduces new issues which the code chokes on. Namely, it finds a node with multiple parents (not as secondary edges): s46234_131. I don't know how to handle that properly, so for now it still raises an exception. In my research I therefore used Tiger v2.1 in the Negra export format.

Another issue with what you're trying to do is that you're converting a discontinuous treebank to a continuous one without a transformation to resolve those discontinuities. I have implemented one such transformation (--splitdisc), but note that it's not the most commonly used one (node raising). Cf. http://hdl.handle.net/10062/15954 for an overview.

**Comment by FilippoC** [comment] 2017-01-13 17:04
Thanks !

Unfortunately I must use the corrected version as I'm working with with both constituent and dependencies (it seems that the corrected version has a different number of sentences).

Is there an export format that support discontinuity ? I can't work with the Tiger format on my computer, it's uses way too much RAM.

**Comment by andreasvc** [comment] 2017-01-13 18:18
On January 13, 2017 6:04:19 PM GMT+01:00, Filippo <notifications@github.com> wrote:
>Unfortunately I must use the corrected version as I'm working with with
>both constituent and dependencies (it seems that the corrected version
>has a different number of sentences).

You can work around this to some extent by matching on sentence IDs.

>Is there an export format that support discontinuity ? I can't work
>with the Tiger format on my computer, it's uses way too much RAM.

Yes, negra's export format and my 'discbracket' format, see discodop docs.
But this means that you can only use tools which support discontinuity.
Getting rid of the discontinuities might be better.

Also, to avoid the exception caused by the errors in the tiger xml, you should replace the raise statement with a pass.

**Comment by andreasvc** [comment] 2017-01-20 22:14
Closing: issue is resolved by using the patch for Tiger 2.2 at https://gist.github.com/andreasvc/7284788

**Closed by andreasvc** 2017-01-20 22:14 UTC
